services:
  pdv-backend-dev:
    container_name: pdv-backend-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3334:3333"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - sqlite_data:/app/prisma
    environment:
      - NODE_ENV=development
    restart: always

volumes:
  sqlite_data:
